trainer:
  epoch: 101
model:
  # for Hayao : 1.2, 1.2, 1.2, 0.8
  # for Paprika : 1.0, 1.0, 1.0, 0.005
  # for Shinkai: 1.7, 1.7, 1.7, 1.0
  real_loss_weight: 1.7
  fake_loss_weight: 1.7
  gray_loss_weight: 1.7
  real_blur_loss_weight: 1.0
  d_lr: 4.0e-5
  g_lr: 2.0e-5
  g_adv_weight: 300
  d_adv_weight: 300
  # 1.5 for Hayao, 2.0 for Paprika, 1.2 for Shinkai
  con_weight: 1.5
  # 2.5 for Hayao, 0.6 for Paprika, 2.0 for Shinkai
  sty_weight: 2.5
  # 15. for Hayao, 50. for Paprika, 10. for Shinkai
  color_weight: 10.
  # 1. for Hayao, 0.1 for Paprika, 1. for Shinkai
  tv_weight: 1
  sn: True

dataset:
  path: "./dataset"
  name: "Hayao"
  batch_size: 8
  num_workers: 4